export const categoriaConsumibles = [
    {nombre: "INSUMOS ALIMENTARIOS"},
    {nombre: "MATERIAL DE LIMPIEZA"},
    {nombre: "MATERIAL DE OFICINA"},
];
export const grupoConsumibles = [
    {nombre: "Aceite vegetal"},
    {nombre: "Acrílico"},
    {nombre: "Agua embotellada"},
    {nombre: "Almendras"},
    {nombre: "Arroz"},
    {nombre: "Avena"},
    {nombre: "Azucar"},
    {nombre: "Café"},
    {nombre: "Caramelos"},
    {nombre: "Cartón"},
    {nombre: "Cartón plastificado"},
    {nombre: "Chocolate"},
    {nombre: "Desinfectante"},
    {nombre: "Detergente"},
    {nombre: "Galletas"},
    {nombre: "Gaseosa"},
    {nombre: "Hojas"},
    {nombre: "Huevos"},
    {nombre: "Jabón"},
    {nombre: "Jugo"},
    {nombre: "Lapicero"},
    {nombre: "leche evaporada"},
    {nombre: "Legumbres y otros granos"},
    {nombre: "Lejía"},
    {nombre: "Madera"},
    {nombre: "Mani"},
    {nombre: "Mantequilla"},
    {nombre: "Manzana"},
    {nombre: "Metal"},
    {nombre: "Pan"},
    {nombre: "Papel higiénico"},
    {nombre: "Plátano"},
    {nombre: "Plumón"},
    {nombre: "Polipropileno"},
    {nombre: "Queso"},
    {nombre: "Soda cáustica"},
    {nombre: "Tinta líquida"},
    {nombre: "Toner"},
    {nombre: "Yogurt"},

];
export const procesoConsumibles = [
    {nombre: "Paper and board for (fat) food packaging"},
    {nombre: "toner module production, laser printer, colour | toner module, laser printer, colour | APOS, U"},
    {nombre: "Life Cycle Comparison Report on a Ballpoint Pen"},
    {nombre: "Water, bottled, processed in FR | Ambient (long) | Already packed - PET | at packaging"},
    {nombre: "Soda, sugar and caffeine"},
    {nombre: "Biscuit"},
    {nombre: "Peanuts, unsalted"},
    {nombre: "Printing Ink, Black, conventional"},
    {nombre: "PP (Polypropylene)"},
    {nombre: "Paper, woodfree uncoated, bleached"},
    {nombre: "Steel hot rolled sheet USA"},
    {nombre: "market for soap | soap | APOS, U - GLO"},
    {nombre: "    Coffee"},
    {nombre: "Cheese, 20+"},
    {nombre: "Granulated sugar"},
    {nombre: "Apple"},
    {nombre: "Oil, sunflower"},
    {nombre: "Yogurt, whole"},
    {nombre: "Oak, European FSC/PEFC 710 (kg/m3)"},
    {nombre: "Butter, salted"},
    {nombre: "Sodium Hypochlorite, NaOCl (Plasticseurope 2013)"},
    {nombre: "Rice, white"},
    {nombre: "Syrup, sweetened"},
    {nombre: "Declaración Ambiental de producto Prodotti Tissue in pura cellulosa per uso igienico e domestico"},
    {nombre: "Chicken egg"},
    {nombre: "Bread, whole wheat"},
    {nombre: "Almonds, without membrane"},
    {nombre: "Chocolate, milk"},
    {nombre: "Board (solid) and recycled paper (test liner and fluting) in Europe"},
    {nombre: "Oatmeal"},
    {nombre: "Banana"},
    {nombre: "Milk, whole"},
    {nombre: "MMA (Methyl methacrylate)"},
];
export const descripcionConsumibles = [
    {descripcion: "ABASTECIMIENTO"},
    {descripcion: "ACADEMICA"},
    {descripcion: "ADMINISTRACION"},
    {descripcion: "ADMISION"},
    {descripcion: "ALIMENTARIAS"},
    {descripcion: "AMBIENTAL"},
    {descripcion: "ASEOSRIA"},
    {descripcion: "ASUNT ACADEM"},
    {descripcion: "BIENESTAR"},
    {descripcion: "CALIDAD"},
    {descripcion: "CIENCIAS"},
    {descripcion: "CONTABILIDAD"},
    {descripcion: "CONTROL INST"},
    {descripcion: "ECONOMIA"},
    {descripcion: "EJECTUTORA"},
    {descripcion: "EMPRESAS"},
    {descripcion: "FORMULADORA"},
    {descripcion: "GENERALES"},
    {descripcion: "GESTION EMPRESARIAL"},
    {descripcion: "GESTION PUBL"},
    {descripcion: "GESTION Y CIENCIAS"},
    {descripcion: "IMAGEN"},
    {descripcion: "INDUSTRIAL"},
    {descripcion: "INGENIERIA"},
    {descripcion: "INVERSIONES"},
    {descripcion: "INVESTIGACION"},
    {descripcion: "MECATRONICA"},
    {descripcion: "PLANEAMIENTO"},
    {descripcion: "PRESIDENCIA"},
    {descripcion: "PRESUPUESTO"},
    {descripcion: "PROYECCION"},
    {descripcion: "RELACIONES"},
    {descripcion: "RENOVABLES"},
    {descripcion: "RH"},
    {descripcion: "SECRETARIA GENERAL"},
    {descripcion: "SISTEMAS"},
    {descripcion: "TECNOLOGIAS"},
    {descripcion: "TESORERIA"},
    {descripcion: "TEXTIL"},
];
export const tipoConsumibles = [
    {nombre: "ACEITE VEGETAL COMESTIBLE", unidad: "kg"},
    {nombre: "AGUA DE MESA SIN GAS X 20 L + ENVASE", unidad: "kg"},
    {nombre: "AGUA DE MESA SIN GAS X 625 mL", unidad: "kg"},
    {nombre: "AGUA DE MESA SIN GAS X 625 mL X 15", unidad: "kg"},
    {nombre: "AGUA MINERAL SIN GAS X 20 L", unidad: "kg"},
    {nombre: "AGUA MINERAL SIN GAS X 355 mL", unidad: "kg"},
    {nombre: "AGUA MINERAL SIN GAS X 625 mL APROX.", unidad: "kg"},
    {nombre: "ALMENDRA (KG)", unidad: "kg"},
    {nombre: "ARCHIVADOR DE CARTON PLASTIFICADO CON PALANCA LOMO ANCHO TAMAÑO OFICIO", unidad: "kg"},
    {nombre: "ARCHIVADOR DE PLÁSTICO DE PALANCA LOMO ANCHO TAMAÑO A4", unidad: "kg"},
    {nombre: "ARCHIVADOR DE PLÁSTICO DE PALANCA LOMO ANCHO TAMAÑO A5", unidad: "kg"},
    {nombre: "ARROZ EXTRA", unidad: "kg"},
    {nombre: "ATUN EN FILETE EN ACEITE VEGETAL X 170 g", unidad: "kg"},
    {nombre: "AZUCAR RUBIA DOMESTICA", unidad: "kg"},
    {nombre: "BEBIDA GASEOSA X 285 mL", unidad: "kg"},
    {nombre: "BEBIDA GASEOSA X 300 mL AMARILLA", unidad: "kg"},
    {nombre: "BEBIDA GASEOSA X 350 mL", unidad: "kg"},
    {nombre: "BEBIDA GASEOSA X 600 mL", unidad: "kg"},
    {nombre: "BOLÍGRAFO (LAPICERO) DE TINTA LÍQUIDA PUNTA FINA COLOR AZUL", unidad: "kg"},
    {nombre: "BOLIGRAFO (LAPICERO) DE TINTA SECA PUNTA FINA COLOR NEGRO", unidad: "kg"},
    {nombre: "BOLIGRAFO (LAPICERO) DE TINTA SECA PUNTA MEDIA COLOR AZUL", unidad: "kg"},
    {nombre: "BOLIGRAFO (LAPICERO) DE TINTA SECA PUNTA MEDIA ECOLOGICO", unidad: "kg"},
    {nombre: "BOLIGRAFO (LAPICERO) TINTA GEL PUNTA FINA COLOR AZUL", unidad: "kg"},
    {nombre: "CAFÉ INSTANTÁNEO X 250 g", unidad: "kg"},
    {nombre: "CAÑIHUA TOSTADA MOLIDA", unidad: "kg"},
    {nombre: "CARAMELO DURO (CIENTO)", unidad: "kg"},
    {nombre: "CHOCOLATE EN PASTA X 400 g", unidad: "kg"},
    {nombre: "CINTA DE PAPEL PARA ENMASCARAR - MASKING TAPE 2 in X 40 yd", unidad: "kg"},
    {nombre: "CLIP DE METAL 33 mm X 101", unidad: "kg"},
    {nombre: "CLIP MARIPOSA DE METAL 45 mm X 53", unidad: "kg"},
    {nombre: "CUADERNO DOBLE ESPIRAL DE PAPEL BOND 90 g 20 cm X 20 cm X 50 HOJAS", unidad: "kg"},
    {nombre: "DESINFECTANTE LIMPIADOR AROMATICO X 3.785 L APROX.", unidad: "kg"},
    {nombre: "DETERGENTE EN POLVO X 15 kg", unidad: "kg"},
    {nombre: "ENGRAPADOR GRANDE DE OFICINA (150 HOJAS)", unidad: "kg"},
    {nombre: "ENGRAPADOR GRANDE DE OFICINA (50 HOJAS)", unidad: "kg"},
    {nombre: "ESENCIA DE PANETÓN X 1 L", unidad: "kg"},
    {nombre: "FOLDER MANILA TAMAÑO A4 COLOR AMARILLO", unidad: "kg"},
    {nombre: "FOLDER MANILA TAMAÑO OFICIO COLOR AMARILLO", unidad: "kg"},
    {nombre: "FRUTA CONFITADA (KG)", unidad: "kg"},
    {nombre: "GALLETA DULCE X 270 g APROX. X 6", unidad: "kg"},
    {nombre: "GALLETA SALADA X 24 g APROX. X 6", unidad: "kg"},
    {nombre: "GALLETA SALADA X 30 g APROX. X 6", unidad: "kg"},
    {nombre: "HOJUELAS DE AVENA (KG)", unidad: "kg"},
    {nombre: "JABÓN DE TOCADOR LÍQUIDO X 3.8 L", unidad: "kg"},
    {nombre: "JABON DE TOCADOR LIQUIDO X 4 L", unidad: "kg"},
    {nombre: "JUGO DE FRUTAS X 350 mL", unidad: "kg"},
    {nombre: "LECHE EVAPORADA ENTERA X 400 g APROX. X 6", unidad: "kg"},
    {nombre: "LEJIA (HIPOCLORITO DE SODIO) AL 6%", unidad: "kg"},
    {nombre: "LENTEJA CALIDAD 2 - SUPERIOR (KG)", unidad: "kg"},
    {nombre: "MANTECA VEGETAL A GRANEL", unidad: "kg"},
    {nombre: "MANZANA CHILENA (AL PESO) (KG)", unidad: "kg"},
    {nombre: "MARGARINA SIN SAL A GRANEL", unidad: "kg"},
    {nombre: "MICA PORTAPAPELES DE POLIPROPILENO TAMAÑO A4 (CIENTO)", unidad: "kg"},
    {nombre: "MOTA PARA PIZARRA ACRILICA", unidad: "kg"},
    {nombre: "NOTA AUTOADHESIVA 3 in X 3 in (7.6 cm X 7.6 cm) APROX. X 500 HOJAS", unidad: "kg"},
    {nombre: "NUMERADOR AUTOMATICO DE METAL DE 8 DIGITOS", unidad: "kg"},
    {nombre: "PAPEL HIGIENICO HOJA SIMPLE BLANCO X 500 m X 4", unidad: "kg"},
    {nombre: "PECANA (KG)", unidad: "kg"},
    {nombre: "PERFORADOR DE 2 ESPIGAS PARA 275 HOJAS APROX.", unidad: "kg"},
    {nombre: "PERFORADOR DE 2 ESPIGAS PARA 45 HOJAS APROX.", unidad: "kg"},
    {nombre: "PLÁTANO DE SEDA ÓRGANICO", unidad: "kg"},
    {nombre: "PLUMON MARCADOR DE TINTA AL AGUA DOBLE PUNTA (PUNTA FINA Y MEDIANA)", unidad: "kg"},
    {nombre: "PLUMON PARA PIZARRA ACRILICA PUNTA GRUESA RECARGABLE COLOR AZUL", unidad: "kg"},
    {nombre: "PLUMON PARA PIZARRA ACRILICA PUNTA GRUESA RECARGABLE COLOR NEGRO", unidad: "kg"},
    {nombre: "PLUMON PARA PIZARRA ACRILICA PUNTA GRUESA RECARGABLE COLOR ROJO", unidad: "kg"},
    {nombre: "PLUMON RESALTADOR PUNTA GRUESA BISELADA", unidad: "kg"},
    {nombre: "PRE MEZCLA DE PANETON", unidad: "kg"},
    {nombre: "QUESO PARIA (KG)", unidad: "kg"},
    {nombre: "SOBRE MANILA TAMAÑO A4", unidad: "kg"},
    {nombre: "SOBRE MANILA TAMAÑO A5.", unidad: "kg"},
    {nombre: "SOBRE MANILA TAMAÑO EXTRAOFICIO", unidad: "kg"},
    {nombre: "SODA CAUSTICA (AL PESO) (KG)", unidad: "kg"},
    {nombre: "SURTIDO DE MANI, PASAS Y HABAS X 250 g", unidad: "kg"},
    {nombre: "TABLERO ACRILICO TAMAÑO A4 CON SUJETADOR DE METAL 176.00", unidad: "kg"},
    {nombre: "TINTA DE IMPRESIÓN PARA EPSON COD. REF. T544120AL NEGRO", unidad: "kg"},
    {nombre: "TINTA DE IMPRESIÓN PARA EPSON COD. REF. T544220AL CIAN", unidad: "kg"},
    {nombre: "TINTA DE IMPRESIÓN PARA EPSON COD. REF. T544320AL MAGENTA", unidad: "kg"},
    {nombre: "TINTA LIQUIDA SOLVENTE PARA CABEZAL DE IMPRESION DE PLOTTER X 1 gal CIAN", unidad: "kg"},
    {nombre: "TINTA PARA ALMOHADILLA DE SELLO AUTOENTINTABLE X 30 mL COLOR AZUL", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA HP COD. REF. 78A CE278A NEGRO", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA HP COD. REF. 85A CE285A NEGRO", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA HP COD. REF. 85A CE285AD NEGRO", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA KONICA MINOLTA COD. REF. TN 514C A9E8430 CIAN", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA KONICA MINOLTA COD. REF. TN 514K A9E8130 NEGRO", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA KONICA MINOLTA COD. REF. TN 514M A9E8330 MAGENTA", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA KONICA MINOLTA COD. REF. TN 514Y A9E8230 AMARILLO", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA KONICA MINOLTA COD. REF. TN 516 NEGRO", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA KONICA MINOLTA COD. REF. TN 618 NEGRO", unidad: "kg"},
    {nombre: "TÓNER DE IMPRESIÓN PARA KYOCERA COD. REF. TK 7227 NEGRO", unidad: "kg"},
    {nombre: "WAFER RELLENO DE VAINILLA X 29 g APROX. X 6", unidad: "kg"},
    {nombre: "YEMA DE HUEVO LIQUIDO (KG)", unidad: "kg"},
    {nombre: "YOGURT X 1 L", unidad: "kg"},
    {nombre: "YOGURT X 1 L SABOR FRESA", unidad: "kg"},
    {nombre: "YOGURT X 180 mL", unidad: "kg"},
];