import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UNAJ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          {/* <Header></Header> */}
          <div className="flex h-full">
            {/* <Sidebar className="w-1/4"></Sidebar> */}
            <div className="w-3/4 border-4 border-gray-200 flex justify-center items-center">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
